### ISSUE TITLE
Space Beavers Return (Kinda)

### ISSUE THREAD

**Issue by Krayolla** [StarQuestMinecraft/StarQuestPublic#720] opened 2015-09-19 15:25 UTC
Alrighty, so I had just returned from Alpha to Raku and landed at the UMD base. After parking underground and unpiloting. The ship had half-way disintegrated. And it actually counted as such when I tried to repilot the ship to get it to regenerate. Blocks were actively missing. However, I've began waiting and noticing that the parts are slowly regenerating now. Not entirely sure if this is a bug or if it's just a loading issue or something.

**Comment by awangatboo** [comment] 2015-09-19 15:39
When was this date / time?  Was the server slow or lagging when this happened?

**Comment by brickworm2012** [comment] 2015-09-19 16:42
Ships tend to disappear in chunks and bits, then reappear. However the hitbox is still there.

**Comment by Krayolla** [comment] 2015-09-19 16:44
Was today, at about approximately 10:30 am CST. Server was minimally laggy, but still slightly. And Brickworm. The hitbox is infact not there. Trust me. I've relogged,Tried various things to get it to continue generating. But many of the blocks in the back half are still missing. Completely gone.

**Comment by Siigillum** [comment] 2015-09-20 19:27
Sometimes after moving between systems/planets ships kinda split in half. Redetecting after entry always solves the problem.

**Comment by Krayolla** [comment] 2015-09-20 19:29
I'll have to point out that it only occured after being on the planet for 2 minutes and then parking my ship. Nor did Redetecting help. It was actively missing blocks that did not re-appear. However, it'd be hard to recreate as I've destroyed the ship in order to build a working one.

**Comment by Mindaugas3** [comment] 2015-09-25 09:55
Had same issue today on Avaquo. The cause (I assume) is stray cannon shots frozen in unloaded chunks. I Had my ship damaged a bit by a stray cannonshot, then I lagged pretty hard so had to force /release to stop autopilot, then noticed i have 45% wool. I had to remove some armor with bare hands(no pick). 
Stray cannonshots is the cause, and I suggest fixing this by deleting the scripted glass blocks once chunk is unloaded.

**Comment by Mindaugas3** [comment] 2015-09-27 11:31
Can confirm. Today on exit from Lagvaquo, I had my ship back torn off. The sign which was attached to wall was still there, while wall of wool was gone.

**Comment by Beachguyryan** [comment] 2016-01-23 13:03
Today 1/23/1016 at 6:30am central time. Disasterstudios lost the back half of his ship while coming into Otavo, Server wasnt laggy and not very many ppl on. He lost all the stuff in the droppers when i reloaded the ship also.

**Comment by awangatboo** [comment] 2016-04-20 18:50
Closing all bugs in preparation for SQ 4.0.

**Closed as completed by awangatboo** 2016-04-20 18:50 UTC
Labels: Priority low
