### ISSUE TITLE
Server jump not working with large ships

### ISSUE THREAD

**Issue by JC3371** [StarQuestMinecraft/StarQuestPublic#1109] opened 2016-07-12 16:15 UTC
On erilon all of my faction members who take small ships were able to leave the atmosphere and come back. I use a bigger ship however and it says "preparing serverjump". I wait a few minutes and nothing happens.

**Comment by Millibyte1** [comment] 2016-07-12 17:10
Closing as duplicate of #1100

**Closed as completed by Millibyte1** 2016-07-12 17:10 UTC
