### ISSUE TITLE
Died while entering atmosphere of Jurion (Possibly beavers?)

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1132] opened 2016-07-19 17:48 UTC
(IGN is miner_guy667)

Alright I was entering the atmosphere of Jurion at around 12:40 EST on Tuesday. After entering the atmosphere I was glitched into the wall of my ship. I relogged and almost immediately died. The death message was "miner_guy667 needed life-alert".

I rushed back to the spot where I had died in a noobfighter and found my ship and dropper contents intact, but the stuff in my inventory had despawned. Inventory screenshot is attached.
[2016-07-20_00 27 38](https://cloud.githubusercontent.com/assets/18903592/16960146/cb5a0494-4e1a-11e6-85a9-e45156a1be49.png)

**Comment by Millibyte1** [comment] 2016-07-19 19:26
Closed as duplicate of #1082, ask a mod ingame to refund you and they will

**Closed as completed by Millibyte1** 2016-07-19 19:26 UTC
