### ISSUE TITLE
Cannot activate turret on some servers

### ISSUE THREAD

**Issue by BatFC** [StarQuestMinecraft/StarQuestPublic#1018] opened 2016-06-09 01:30 UTC
Turret is not activating (newly placed turret sign not changing when clicked) on Arator, Tyder and Arator space servers. I know the turrets were built right because they activate just fine on Jurion.

**Comment by sergio-carli** [comment] 2016-06-09 13:34
Yes this also happens to me.

**Comment by buba141** [comment] 2016-06-13 20:12
I could not reproduce this on Tyder, but it does happen on Arator and in Arator space. Should be fixed after the next restart.

**Comment by GingerWalnut** [comment] 2016-06-14 23:18
This is fixed

**Closed as completed by GingerWalnut** 2016-06-14 23:18 UTC
