### ISSUE TITLE
Lost Inventories Entering Gamma

### ISSUE THREAD

**Issue by GoldPikachuSpark** [StarQuestMinecraft/StarQuestPublic#502] opened 2015-06-24 19:30 UTC
xLordHerobrinex and I (Goldieh) timed out while entering the Gamma system. When we joined back our inventories were gone and our ship but i was in Gamma and Herobrine was in Alpha still (near the slipgates).

**Comment by awangatboo** [comment] 2015-07-08 13:12
This is an issue for the Mods IF you need your stuff back.  If you think it is a Bug in some since please state how to reproduce.  I know loads of people have been going back and forth between Gamma and Alpha without issues.  

If it can not be reproduced please close this github ticket so Dib can get to the important ones that cause issues for the whole server.

**Comment by awangatboo** [comment] 2015-08-04 12:52
Closing as an old ticket

**Closed as completed by awangatboo** 2015-08-04 12:52 UTC
