### ISSUE TITLE
Issue with bat disguise

### ISSUE THREAD

**Issue by Kyle98martin** [StarQuestMinecraft/StarQuestPublic#617] opened 2015-07-19 09:55 UTC
LightningDuck104 pointed out on the forums that he did not receive his bat disguise after purchasing it. I then checked my disguises to also notice that my bat disguise was also missing but all my other disguises remained the same. I do not how long this has been an issue as I didn't really use my disguises so this was the first time I've heard anything of it. It may be happening with other disguises but bat is the only one I can confirm

**Comment by awangatboo** [comment] 2015-08-09 01:17
This is a duplicate of #481 except for it is a bat.  Closing as #481 has way more debug info in it.

**Closed as completed by awangatboo** 2015-08-09 01:17 UTC
