### ISSUE TITLE
Got killed coming into Trinitos Alpha

### ISSUE THREAD

**Issue by AlternatePFG** [StarQuestMinecraft/StarQuestPublic#542] opened 2015-06-29 04:55 UTC
I lost my ship, and armor. Me and Alex were talking about how respiration works with space helmets as I came through. Instead of allowing me to come with my ship. It wiped my inventory, and made me fall into the void with my ship being in TA (I think).

I have a screenshot of the death, and outdated-ish screenshots of my armor. My bow however, I don't have pictures of, it was a Power IV, Unbreaking III, Flame I, Infinity I bow. Along with gold ingots (which I don't care about). I really just care about the gear I lost such as the god armor, sword, and my efficiency 4 unbreaking 3 pick.

http://screencast.com/t/x46A1xSBG3b Death

http://imgur.com/a/cvgi8 My armor, sword, and not the pick I had on me.

Please refund dis senpai?

P.S Sorry if refunds still aren't allowed, I thought that policy was changed back.

**Comment by awangatboo** [comment] 2015-07-09 21:05
This issue happens when the server you are getting warped to is down.  This is a known issue and not a Bug.  Talk to mods about a refund but if you have flown another ship or gone into Alpha since your death you will not be able to get a refund, 

Please take up with the Mods on the Refund and Close this Ticket

**Closed as completed** 2015-08-16 00:47 UTC
