### ISSUE TITLE
Chest Fix limiting Machina Factory

### ISSUE THREAD

**Issue by soronthar** [StarQuestMinecraft/StarQuestPublic#965] opened 2016-05-29 00:40 UTC
I found out that if the end point of a machina factory (i.e a chest) is more than 6 blocks from the player when the lever is activated, then  the chestfix message will be displayed and the factory will not activate.
Tested on Quillon

**Comment by PatchyFox** [comment] 2016-05-29 14:57
... Interesting discovery on the 6-block test. Confirmed results on Arator. 

Fundamentally, this would break most factory types entirely, as the design is longer than 6 blocks from end to end.

**Comment by Laserlance141** [comment] 2016-05-29 16:20
Also if you use an activator to start the factory, and you are more then 6 blocks away from the starting inventory, it has the same problem

**Comment by dphfox** [comment] 2016-05-31 13:28
The 6-block limitation is to do with how ChestFix works. ChestFix, as well as stopping you from using stuff you can't see, also stops you from using things that are out of reach, and that radius is about 6 blocks. I believe that this is the cause of the problem.

**Comment by Denyol** [comment] 2016-06-02 00:37
This issue should be resolved soon.

**Comment by awangatboo** [comment] 2016-06-02 11:40
I have been told that a fix for this has been installed.

**Closed as completed by awangatboo** 2016-06-02 11:40 UTC
