### ISSUE TITLE
My Cert got taken away

### ISSUE THREAD

**Issue by genaraldiamond** [StarQuestMinecraft/StarQuestPublic#645] opened 2015-08-02 00:52 UTC
I gathered all the items for a drill, then got all of the points and money to purchase the resource engineer cert, i did /cert unlock 10 (10 was the id for resource engineer for me) it gave me the message that the cert was purchased then I went to the drill to use it, then it told me i don't have permission to operate it, i then did /cert tag and it had altogether disappeared from my cert list, I never delete any of my certs, so there is no chance of accidental deletion, and when i checked it is back in my cert unlock list, where it wasn't there anymore before! Please help me! When I unlocked the cert i had all the required points and it gave me the cert when I did /cert tag but like 5 mins later it had disappeared from my certs and went back onto my cert unlock list!

**Comment by awangatboo** [comment] 2015-08-02 02:15
This is not a bug.

http://starquestminecraft.com/starquesthome/m/17590832/article/3406188/page/2

Please close this ticket

**Closed as completed** 2015-08-02 13:28 UTC
