### ISSUE TITLE
Planterdrill Cert Broken

### ISSUE THREAD

**Issue by HiFlyCS** [StarQuestMinecraft/StarQuestPublic#576] opened 2015-07-10 05:18 UTC
Can't operate Planters. I have 9 smuggling points and the planterdrill cert + tag.

**Comment by awangatboo** [comment] 2015-07-10 12:59
This is a duplicate of #561.  Please close.  I will put in #561 that the tag is missing as well.

**Closed as completed** 2015-07-16 03:08 UTC
