### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by rocky0121** [StarQuestMinecraft/StarQuestPublic#789] opened 2015-12-29 00:41 UTC
java turned mob spawning and monsters on in tsa otavo base, yet no poison spiders are spawning within our claim (we have a grinder) is this a bug?

**Comment by Evancooldude** [comment] 2015-12-29 03:31
First, are you certain that your spawning conditions are right for them? I'll ask about it though.

**Comment by Siigillum** [comment] 2016-01-03 11:38
This is a feature.

**Comment by Evancooldude** [comment] 2016-01-03 15:51
I see. Thank you.

**Comment by rocky0121** [comment] 2016-01-04 02:44
no but monsters was on

**Comment by awangatboo** [comment] 2016-01-04 13:08
after talking to Dib SQ uses a custom mob spawner.  There a specific rules about mobs spawing in faction land.  Do like everyone else build your exp / mob drop grinder outside of your faction.

**Comment by rocky0121** [comment] 2016-01-04 23:50
??

**Comment by Evancooldude** [comment] 2016-01-05 00:08
It's supposed to be that way, build your grinder outside your faction claim.

**Comment by rocky0121** [comment] 2016-01-05 00:13
yah already on it

**Comment by Evancooldude** [comment] 2016-01-05 03:16
I'm going to close this, as it's not a bug.

**Closed as completed by Evancooldude** 2016-01-05 03:16 UTC
