### ISSUE TITLE
Crypods Break When On SHip

### ISSUE THREAD

**Issue by DirtierCow41** [StarQuestMinecraft/StarQuestPublic#1182] opened 2016-08-09 00:52 UTC
The Cryopods will occasionally  break when the server restarts or there is a glitch with the ship or just randomly too.

**Comment by Millibyte1** [comment] 2016-08-09 19:08
Could you give any more information on the cryopod's state when this bug repros?

**Comment by Millibyte1** [comment] 2016-08-13 21:26
Closed as duplicate of #1027

**Closed as completed by Millibyte1** 2016-08-13 21:26 UTC
