### ISSUE TITLE
Death Teleportation

### ISSUE THREAD

**Issue by Starsword7** [StarQuestMinecraft/StarQuestPublic#589] opened 2015-07-13 22:03 UTC
Every time someone dies then re spawns, they are teleported into space, suffocate, then teleported to the spawn of the planet they where on, then finally teleported to their cryopod.

**Comment by awangatboo** [comment] 2015-07-13 22:28
Is this with a cryopod that is on a ship or any cryopod?

**Comment by Starsword7** [comment] 2015-07-14 13:12
a cryopod on a planet. This has happened to me multiple times with different cryopods on different planets

**Comment by ice20039** [comment] 2015-07-16 15:57
I can confirm this

**Comment by gregolegomonkey** [comment] 2015-07-16 19:10
I had the same issue where I fell from my ship on Uru and died (due to client lag, not bug).  I didn't have a cryopod set, and it spawned me somewhere in space where I suffocated, then spawned back at spawn in TA.

**Comment by awangatboo** [comment] 2015-07-16 19:26
you might want to /removehome and then rebuild your cryopod.

**Comment by awangatboo** [comment] 2015-08-04 14:27
Has this still been an issue after /removehome and rebuilding a cryopod?

**Comment by awangatboo** [comment] 2015-08-09 01:49
Closing this bug in order to obtain better details in current Cryopod issues.  If you have another Cryopod iss please see this forum thread before opening a new issue.

http://www.starquestminecraft.com/starquestforums/m/17078810/viewthread/23552021-great-cryopod-bug-closing/post/last#last

**Closed as completed by awangatboo** 2015-08-09 01:49 UTC
