### ISSUE TITLE
liliaga Guest When in Yavari

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/StarQuestPublic#935] opened 2016-05-22 00:13 UTC
![2016-05-21_17 12 31](https://cloud.githubusercontent.com/assets/10093818/15451444/6a7c62f6-1f77-11e6-8e04-54e109f0bb46.png)
liliaga is in Yavari, but he's still  a guest. I'm pretty sure at least. I haven't seen him type in chat, but MemeLord said he was still a guest.

**Comment by gregolegomonkey** [comment] 2016-05-22 00:57
He might be a victim of a REALLY nasty rankup bug, but I doubt it considering that his power level is less than 100.

**Comment by awangatboo** [comment] 2016-05-23 14:39
This will need to be fixed by a manager or maybe even Dib.  Have this player contact a manager when in game.

**Comment by buba141** [comment] 2016-06-13 18:54
This was probably caused by the same bug as #1008, which has been fixed.

**Closed as completed by buba141** 2016-06-13 18:54 UTC
Labels: Priority Med
