### ISSUE TITLE
REQUIEM to core gate borked

### ISSUE THREAD

**Issue by CrazyCreeper1o1** [StarQuestMinecraft/StarQuestPublic#1163] opened 2016-07-27 09:22 UTC
I was flying on over to Xira just now but when I flew through slipgate number two in Quillon space, my ship vanished along with my inventory and I was respawned back on the REQ spawnship

**Comment by Millibyte1** [comment] 2016-07-31 17:39
Closing as duplicate of #1144

**Closed as completed by Millibyte1** 2016-07-31 17:39 UTC
