### ISSUE TITLE
Ship duplication error

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1065] opened 2016-06-29 11:58 UTC
Hi there, 

Over the weekend, when planet movement was introduced in the core, the server reset while I was in core space, which somehow resulted in a line of ~20 copies of half of my ship appearing in a solid line near the old Xira server jump. 

Initially, reported in-game to EvanesarCaesar, who I assumed would take care of it. After several hours of resets and downtime, I figured would be a good idea to clear out the cannons and move the ships somewhere they wouldn't be abused - until someone could get rid of 'em. 

Grabbed most of the cannons, flew away, wound up hitting Xira again, where I experienced a server issue that moved my ship to Xira, wiped my inventory and left me in space to suffocate. Lost a fair amount of what was taken to the void, but happy to attempt to round up anything I can give to convince you that I don't care about a mountain of sponge in the slightest. 

Came back: Dragged 5-6 ships back to Arator - LittleBro assisted me later in moving a few more to Tyder. He let me know he was going to report the error to Money, and mentioned he'd told a few other managers. I assumed someone would reach out later, but heard nothing else throughout the weekend. 

Let me know what you want me to do about all this. Feel free to nuke the line of ships on Ara - they're already mostly lined up and ready for deletion. 

-Patchy

**Comment by mcdouble** [comment] 2016-07-03 01:00
Can confirm.

**Comment by Millibyte1** [comment] 2016-07-06 16:19
Is this still occurring? This should be fixed as of Saturday

**Comment by mcdouble** [comment] 2016-07-10 14:08
There's evidence of it on Xira in 1-2 places.

**Comment by Millibyte1** [comment] 2016-07-10 16:14
Going ahead and closing this since the issue this was caused by got fixed a little over a week ago. Could you get a mod to WE the ships out?

**Closed as completed by Millibyte1** 2016-07-10 16:14 UTC
