### ISSUE TITLE
Server Transfer TPs Players into Walls

### ISSUE THREAD

**Issue by CrazyCreeper1o1** [StarQuestMinecraft/StarQuestPublic#1191] opened 2016-08-13 20:40 UTC
Before I thought this was a common thing since it happens almost every time I enter and leave a planet's atmosphere, but Molly told me it doesn't happen that often. It started happening a few weeks ago when I finally escaped with the help from a mod after I waited for five to ten minutes. I was stuck even longer when I was trying to help JUSA defend from Cutout. That time, I tried logging out and back in which seems to work. More recently I realized typing /stopriding works just ass well. The problem is sometimes players get TPd outside their ship when they do get out, or at least me, but I don't take fall damage. The biggest problem is when you fall into the middle of a super deep ocean.

**Comment by Millibyte1** [comment] 2016-08-13 21:24
Closed as duplicate of #1082

**Closed as completed by Millibyte1** 2016-08-13 21:24 UTC
