### ISSUE TITLE
Invisi Potions not Working

### ISSUE THREAD

**Issue by estudier** [StarQuestMinecraft/StarQuestPublic#960] opened 2016-05-28 11:49 UTC
Still visible on dynmap while invisible.

**Comment by JavaInvader** [comment] 2016-05-28 22:42
this is suppose to be a thing, Except in the core

**Comment by awangatboo** [comment] 2016-05-29 13:09
From what I understand this is something left from 2.0 and the design team has not decided exactly how it will work so this is not a bug.  Closing.

**Closed as completed by awangatboo** 2016-05-29 13:09 UTC
