### ISSUE TITLE
Big ole glitch

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#644] opened 2015-08-01 11:24 UTC
so i was flying on Eratoss with autopilot on when i suddenly started falling out of my ship. My ship suddenly started flying random directions as im falling out of my ship. the ship hit the worldbarrior and i was kicked from the server (i think it was for spam or something i dont rember). when i rejoined i fell to my death and my cryopod spawn did not work so i ended up respawning at spawn. i then built a new ship and headed back to Eratoss to collect my belongings and my ship. When i got there none of my items where on the ground and 1/2 my ship was missing. I know it was not a player because i used dynmap to watch my wreckage the hole time. i also know that my items did not despawn because i got back to the sight in under 10 min. and in order for items to despawn someone has to be close to the items for the chunks data to even load in (i know because one time i died at a spawn station and came back 2 days irl later and the items where still there). No i do not have a screenshot of the ship or my invintory so i know it all is unrecoverable so i am just posting this to let everyone know about the bug.

**Comment by awangatboo** [comment] 2015-08-01 11:28
Please add approximate date and timings so that the Dev's can see what happened in the logs.

**Comment by AlinaFicalton** [comment] 2015-08-01 21:26
it haaponed at around 5am 8/1/15

**Comment by Siigillum** [comment] 2015-08-02 13:32
Sometimes when you enter atmosphere your ship is split in 2 parts, you keep controll on one part only. It's advised to redetect after entry. This might have happened here.

**Comment by AlinaFicalton** [comment] 2015-08-02 18:21
i was in the atmosphere of the planet a good 2 min before this happoned

**Comment by awangatboo** [comment] 2015-08-05 19:39
The more I look at this original bug I see different issues.  I think they should be split into different bugs.

First Bug - Strangeness in auto-piloting ship?  ( as this happens when LAG is high I am not sure this will be fixed any time soon )

Second Bug - World Border is not working like in SQ 2.0 and stopping ship.  Duplicate of #567 

Third Bug - My Cryopod did not work correctly.  Duplicate of to many bugs to list. But please give all the info.

Forth Bug - items despawn too quickly when I do not think the should.

Could you please make different bugs and then lets close this big one as we can try to deal with each issue one at a time.

**Closed as completed** 2015-08-09 08:17 UTC
