### ISSUE TITLE
Slipgates not working + arator ship spawns blocked.

### ISSUE THREAD

**Issue by finnytom** [StarQuestMinecraft/StarQuestPublic#1178] opened 2016-08-04 10:10 UTC
Hello, I tried to go to the south slipgate at -650, 65, 3000 in the Arator Space System, and it says "entering core system", like it should, but then I get teleported to the Arator Space Spawn in the Medical Bay. I lost all my stuff I was taking to the Core System, and the ship I used. I didn't die, so I didn't get teleported to my cryopod. To make matters worse, I tried buying a ship so I could get back home. One of the hangars had some excess wool in it, so it touched the ship I bought and because of that, I couldn't pilot my new ship. It came with the lovely message, "Your ship cannot be more than 2000 blocks!". I tried another hangar, bought another ship, and piloted it just fine. Except for the fact that a ship was exactly right outside the stained glass door so I couldn't fly my ship out into space. I told someone and they said I can type /suicide to get back to my cryopod, which actually worked. All in all, I lost a ship, all my items, 11400 credits, and -2 power. All I wanted was some glowstone. :(

Extra info: The slipgates hasn't been working for a week, this is my second time attempting to go to the core system.

Thanks, finnytom

**Comment by Millibyte1** [comment] 2016-08-04 15:28
Closed as duplicate of #1004

**Comment by Millibyte1** [comment] 2016-08-04 15:28
Ask a mod in game for a refund

**Closed as completed by Millibyte1** 2016-08-04 15:28 UTC
