### ISSUE TITLE
Cannot place blocks in certain areas.

### ISSUE THREAD

**Issue by Arjuncraft2001** [StarQuestMinecraft/StarQuestPublic#369] opened 2015-04-10 17:49 UTC
Ok so i have a big mix of factories in one area and I can't place blocks in some areas. Nick confirmed in creative that he can't either. I am not sure whether this is vanilla, but I am pretty sure this has to do with Machina Factory since it doesn't happen anywhere else. The coords are (-1562, 85, 205) on Valadro.

**Comment by brickworm2012** [comment] 2015-04-11 15:27
Glitchy towny?

**Comment by Dibujaron** [comment] 2015-04-13 21:16
@Arjuncraft2001 I went to the place and could not reproduce the error. I guess it went away on restart. Let me know if it happens again and thanks for reporting!

**Comment by Dibujaron** [comment] 2015-04-14 00:03
believed to be duplicate of #375

**Closed as completed by Dibujaron** 2015-04-14 00:03 UTC
