### ISSUE TITLE
Ship autopilot bug(part III)

### ISSUE THREAD

**Issue by Mindaugas3** [StarQuestMinecraft/StarQuestPublic#774] opened 2015-12-05 20:30 UTC
It happened around 4:48 PM (UTC + 2:00), after assaulting a faction(ACR, let by williamkaller), I was flying with my friend(IGN: neptune777, he has a cyan nickname, and he was flying his fighter(15 bps) while i was flying my maxed courier, finally he flew to Tallimar). We were assaulting and later flying back home on Avaquo, the planet which is very infamous for lag and autopilot which will refuse to stop. I had to fly next to worldborder which was located in northwest from spawn and southwest from my faction, and when i autopiloted again, some part of ship was cut off while autopiloting back home. My ship was maxed courier(Speed 3, Armor 2). No screenshot available, Oldskoolish and kray refunded me.

**Comment by Siigillum** [comment] 2015-12-06 01:33
Lithuanian drivers have a terrible reputation in Poland. They often end up with parts of their cars cut off too (usually after contact with a random tree or concrete barrier).

Coincidence?

**Comment by Mindaugas3** [comment] 2015-12-06 07:43
Probably yes, but then I'd be dead and there would be a wreck if that was an intended feature. However, standalone turret sign is not that easy to make(while it is true that i often hug trees, or go into random wrecks in air, or even cobble towers/nerdpoles. Lol)

**Comment by awangatboo** [comment] 2015-12-07 01:22
Mind If this is the same issue please figure out how to reproduce it.

**Comment by awangatboo** [comment] 2015-12-07 01:23
Duplicate of #762 - Closing.  

If these is something different let me know and I will re-open it.

**Closed as completed by awangatboo** 2015-12-07 01:23 UTC
