### ISSUE TITLE
Potions turned into water bottles when leaving atmosphere

### ISSUE THREAD

**Issue by buba141** [StarQuestMinecraft/StarQuestPublic#922] opened 2016-05-16 02:19 UTC
Shocklor/paddy had a doublechest worth of strength potions in his ship's droppers, but they all turned into water bottles when he flew to another planet.

**Comment by awangatboo** [comment] 2016-05-16 21:11
duplicate of #863

**Closed as completed by awangatboo** 2016-05-16 21:11 UTC
