### ISSUE TITLE
Infinite Sign glitch

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#1101] opened 2016-07-11 02:43 UTC
Hey there,

Discovered a bug that allows for a near infinite shower of free signs. Not sure what good 10,000 signs would be, but... figured I'd report it.

It's complex to say the least:

When a block that supports a sign is blown up, and the server attempts to regenerate the sign before a support block is regenned, the sign will drop as an item. If the player destroys the regenned support block before a sign can regenerate on it, the sign will attempt to regen in air, and will drop signs infinitely.

Discovered on Arator. Much sign.

Thanks,

**Comment by Millibyte1** [comment] 2016-07-11 03:13
Closed as duplicate of #1037

**Closed as completed by Millibyte1** 2016-07-11 03:13 UTC
