### ISSUE TITLE
Skywatch

### ISSUE THREAD

**Issue by GirlArcher** [StarQuestMinecraft/StarQuestPublic#700] opened 2015-08-30 04:02 UTC
Ok My Ship Was Stuck To Someone Else's Ship And They Were Online So I Asked TheBeaver To Fix It He Came And Told Me How To Get It Out So When I Was Fixing It The Other Persons Ship Owner Started Attacking My Ship And I Hit Him/She One Time to Warn Them And Skywatch Came Right After One Hit And Attacked Me Till I Was Dead And I Lost Full Diamond Armor Prot 1 And A Kb2 Sharp 2 Sword And A Power 2 Bow And A Ship

**Comment by GirlArcher** [comment] 2015-08-30 04:03
And A Ship

**Comment by GirlArcher** [comment] 2015-08-30 04:13
Thank You

**Comment by HollywoodSun** [comment] 2015-08-30 05:35
I don't think this is a bug. Skywatch is a feature, not a bug.

**Comment by GirlArcher** [comment] 2015-08-30 05:56
Well The First time you hit a player its a warnin the second time they kill you I hit him once
and my ship  glitched into another persons ship.

**Comment by awangatboo** [comment] 2015-08-30 21:39
Did your armor have thorns or did your sword have fire on it?  Sky-watch is called based on damage and if you hit them once and they hit you once but you had thorns on then it equals two hits by you.  Also if your sword has fire you hit them once but the fire damage is counted against you so Sky-watch would come.

**Comment by xGirlWolf** [comment] 2015-08-30 22:20
Ok it happened to me but i used a friends account to make it now i have made my own

**Comment by xGirlWolf** [comment] 2015-08-30 22:20
And No it did not have thorns or fire on it and i used my fist to hit them as a warnin

**Comment by awangatboo** [comment] 2015-08-30 23:03
I have asked someone to look at the server logs.  Let's see what can be found.

**Comment by xGirlWolf** [comment] 2015-08-30 23:51
Thank you

**Comment by awangatboo** [comment] 2015-08-31 12:49
I was thinking on this but I wonder if SkyWatch is programmed not for how many hits but how much damage.  If it was how much damage and you had a diamond sword and they had no armor then this would make since.

**Comment by xGirlWolf** [comment] 2015-08-31 23:22
I Hit them with my fist

**Comment by xGirlWolf** [comment] 2015-08-31 23:22
not with my sword

**Comment by awangatboo** [comment] 2015-09-02 15:23
From what I have been told by the person looking at the logs it is unclear if skywatch glitched.  Adding this to the info we have on skywatch bugs but closing the ticket.

**Closed as completed by awangatboo** 2015-09-02 15:23 UTC
