### ISSUE TITLE
landing gear glitch

### ISSUE THREAD

**Issue by Siscoqu08** [StarQuestMinecraft/StarQuestPublic#431] opened 2015-05-03 19:51 UTC
When i was landing my ship i noticed i didn't hear the pistons drop, when i left the ship they were completely gone.

**Comment by Dibujaron** [comment] 2015-05-04 16:47
Interesting bug but I can't get it to happen to me. Anyone else have this happen?

**Comment by Kyle98martin** [comment] 2015-05-04 16:51
It happened once before on Quav a few months back. When you piloted a ship all the pistons on the ship despawned. The issue resolved itself after about 2 hours and I haven't heard any other cases since then.

**Comment by awangatboo** [comment] 2015-08-04 13:39
Was this a SQ 2.0 only bug or has this been seen in SQ 3.0? 

If no response I will close on 8/11/2015

**Comment by Thedrew655** [comment] 2015-08-11 22:46
I have had this happen to me a few times, most recently a few days ago on SQ 3.0, it usually occurs after piloting and landing multiple times within a short period of time, I will attempt to gather more evidence to what causes it.

**Comment by awangatboo** [comment] 2015-09-02 16:10
duplicate of #268

**Closed as completed by awangatboo** 2015-09-02 16:10 UTC
Labels: No Repro, Priority low
