### ISSUE TITLE
Netherwart dissapears

### ISSUE THREAD

**Issue by cloudtail** [StarQuestMinecraft/StarQuestPublic#537] opened 2015-06-28 16:38 UTC
When right clicking with netherwart on avaquo I got the restricted item message and the whole stack dissapeared from my inventory.

**Comment by Nickmiste** [comment] 2015-06-28 18:02
Netherwart is only able to be grown on Xylos.

**Comment by GroxTerror** [comment] 2015-07-02 05:15
I think he's saying he was just trying to transport it back not plant it, and it disappeared.

**Comment by cloudtail** [comment] 2015-07-17 11:52
no, literaly, if you hold and right click, it dissapears

**Comment by awangatboo** [comment] 2015-08-16 01:16
I can not reproduce.  Is this still an issue?

**Comment by awangatboo** [comment] 2015-08-17 15:57
Cloudtail please comment or I will assume that this is no longer an issue.

**Comment by awangatboo** [comment] 2015-09-02 15:52
Seeing that I cannot reproduce and Cloudtail has not responded I am closing this ticket

**Closed as completed by awangatboo** 2015-09-02 15:52 UTC
