### ISSUE TITLE
Modpack Crashing

### ISSUE THREAD

**Issue by ArcticNebula** [StarQuestMinecraft/StarQuestPublic#545] opened 2015-06-29 17:23 UTC
I was mining on Uru and I came across copper/redstone ore. Whenever I see one I always crash and have to start up the modpack again. This doesn't happen with any other block. It's slightly annoying because then I have to wait to get my spot back since I do not have priority. If this issue can be looked into and fixed it would be appreciated! Thanks in advance!

**Comment by awangatboo** [comment] 2015-07-09 20:09
I know someone else that has the same issue as you.  I am not 100% sure it is the teckit modpack or something with the video card / driver that is driving the game.  Just to try to help with this I will test on my computer tonight to see if this can be reproduced.

**Comment by awangatboo** [comment] 2015-07-09 22:55
I just used the Technic Launcher pack and came across Redstone blocks no issue.  The person that I know that has this same issue has an Nvidia 9xx series card.  Is this the same for you?  Mine is an Nvidia 770 and I have no issues.

**Comment by ArcticNebula** [comment] 2015-07-10 01:41
Firstly, I'd like to thank you for helping me. :)
I'm a complete noob at stuff like this. Are those graphic cards? If so, I don't believe that's what the computer I'm on is using.

**Comment by awangatboo** [comment] 2015-08-04 13:24
Is this still an issue?

**Comment by ArcticNebula** [comment] 2015-08-09 20:11
Yes

**Comment by awangatboo** [comment] 2015-08-09 20:27
Every computer has a graphics card unless they do not have a monitor hooked up to them,  What version of Windows are you using and I hopefully can walk you through finding out and then checking the driver.

**Comment by ArcticNebula** [comment] 2015-08-11 02:50
Unfortunately, I am on a Mac. Sorry to complicate things further.

**Comment by awangatboo** [comment] 2015-08-11 12:32
Oh wow then I am not sure how to try to update your graphics driver.  I know that you can just have no clue how to.

**Comment by ArcticNebula** [comment] 2015-08-14 00:09
Are you sure it may because of the graphics card though? On my vanilla minecraft I use the same resource pack as the modpack does, and when I look at redstone/copper it doesn't crash the game. I think it has something to do with the modpack.

**Comment by awangatboo** [comment] 2015-08-17 15:56
That might be the case but I did talk to the other user that had the same issue as you and he was on a PC using windows and when he upgraded his Video drive the problem went away.  I am not sure what the issue is here or how to fix it.

**Comment by awangatboo** [comment] 2015-09-02 15:51
Seeing that this does not happen to everyone using the mod pack I am putting it as a low priority

**Comment by Evancooldude** [comment] 2015-10-20 20:40
Similar issues have occured on other servers, in some very rare corner cases. It usually has to do with the modpack interpreting visual information in a way that some specific graphics cards aren't set up to handle. This issue would almost definitely have to be solved via changing the visual methods of the modpack, and even possibly a hardware issue. I'm of no use in that area. I don't forsee this ever being worked on.

**Comment by awangatboo** [comment] 2016-04-20 18:57
Closing all bugs in preparation for SQ 4.0.

**Closed as completed by awangatboo** 2016-04-20 18:57 UTC
Labels: Priority low
