### ISSUE TITLE
Kit Spacesuit Broken

### ISSUE THREAD

**Issue by Laserlance141** [StarQuestMinecraft/StarQuestPublic#595] opened 2015-07-14 16:53 UTC
When i tried to use the kit it popped up an error message, and when i tried to do it again it said i had to wait a week to try again
![2015-07-14_09 48 03](https://cloud.githubusercontent.com/assets/13091148/8679223/2e7e21e0-2a0e-11e5-9420-4d3fd3bdcc8c.png)

**Comment by awangatboo** [comment] 2015-07-14 19:11
This is a duplicate of #586 Please close and put any new information in #586.

**Comment by awangatboo** [comment] 2015-07-14 19:12
Oh yeah the reason I say it is a duplicate is even though you have a ~ 7 day timeout it does not work for anyone yet.

**Closed as completed** 2015-07-14 19:43 UTC
