### ISSUE TITLE
Contract Stack size wrong for snowballs

### ISSUE THREAD

**Issue by Tonlage** [StarQuestMinecraft/StarQuestPublic#622] opened 2015-07-21 14:45 UTC
Then looking the number of snowballs that is required to complete a contract the number of stacks shows as if snowballs can be stacked up to 64 and not 16.

**Comment by awangatboo** [comment] 2015-07-21 14:57
There are many contracts that think items can be stacked with stack size 64.  This does not change functionality of the game and should be a low priority.

BTW - Same for mushroom stew.

**Comment by awangatboo** [comment] 2015-09-02 15:46
Would be nice to have fixed but does not stop gameplay

**Comment by Evancooldude** [comment] 2015-10-20 20:42
This bug has been fixed. Since I evidently don't have the ability to close this, I'll ask that Awang or Dib do so.

**Comment by awangatboo** [comment] 2015-10-21 13:43
Has anyone got a snowball contract on the server and confirmed this?

**Closed as completed** 2015-12-10 03:48 UTC
Labels: Priority low
