### ISSUE TITLE
Machina drills don't like doubletall flowers

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#618] opened 2015-07-20 01:34 UTC
Rose bushes, sunflowers, lilacs, etc.

**Comment by awangatboo** [comment] 2015-07-20 11:43
This is a duplicate of #112.  There are many of the newer block types that the drill will not go through.  Please close this Ticket and add the information to #112.

**Closed as completed** 2015-07-20 11:44 UTC

**Comment by lawrencethefrog** [comment] 2015-07-20 12:50
Closed as duplicate of #112
