### ISSUE TITLE
Tonight's Beaver Adventure

### ISSUE THREAD

**Issue by mcdouble** [StarQuestMinecraft/StarQuestPublic#1089] opened 2016-07-07 04:17 UTC
Upon Jurion entry I was beavered - loadship fixed.
Return entry to tyder I was beavered - loadship _fixed_

After the loadship, I flew back to base, moved building supplies around, and set to work on my tower. I relaunched, realizing I was on optifine not schematica. I logged off to relaunch around 12:10ish EST and relogged in about 2 minutes ago at 12:13 EST and I was logged in at the location my ship was beavered,with the inventory I entered atmosphere with. I am unsure whether or not I lost the 2 droppers of items, and if I lost the items I had on me when I logged off. 

This caused me to lose 10 stacks quartz blocks, 5 stacks iron bars, and a stack of glowstone. I didn't screenshot in time because I didn't realize this would happen, but I'm REALLY trying to get this stuff refunded because it took me a long time to get with all the Beaver bugs lately.

**Comment by Millibyte1** [comment] 2016-07-09 23:07
Closing as duplicate of #1090

**Closed as completed by Millibyte1** 2016-07-09 23:07 UTC
