### ISSUE TITLE
Ship glitched, all dispensers, signs, etc gone

### ISSUE THREAD

**Issue by AnonymousLemur** [StarQuestMinecraft/StarQuestPublic#1081] opened 2016-07-05 20:41 UTC
Went to enter planet Quillion, and upon entry, ship's signs had disappeared along with all dispensers, stairs, doors, and a crafting table and furnace. My IGN is -X-Anonymous-X-- (replace dashes with underscores, github's weird), and it happened yesterday at about 4:00, my time (Nevada, whatever timezone that is). The day was 7/4/16.

**Comment by AnonymousLemur** [comment] 2016-07-05 20:42
My IGN is _X_Anonymous_X__, and it happened yesterday at about 4:00, my time (Nevada, whatever timezone that is)

**Comment by martinjonsson01** [comment] 2016-07-05 20:48
I believe this was fixed today, right @evanaesarcaesar ?

**Comment by Millibyte1** [comment] 2016-07-05 22:25
I didn't put in anything that would change this so far as I know, but I've been having difficulty replicating this bug and don't know the root cause. All the transfers today since last restart have been fine, but going to leave it open for now

**Comment by Millibyte1** [comment] 2016-07-06 16:14
Closed as duplicate

**Closed as completed by Millibyte1** 2016-07-06 16:14 UTC
Labels: Duplicate
