### ISSUE TITLE
ships are destroyed upon re entry

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/StarQuestPublic#1092] opened 2016-07-07 21:36 UTC
ok so, sometimes IF you re enter your planet and your ship is there, it'll usually be missing large amounts of blocks

**Comment by gregolegomonkey** [comment] 2016-07-07 22:25
More information, please.  When, where, what, etc.  As much information as you can provide.

**Comment by ghost** [comment] 2016-07-08 05:36
not much else, i left a planet, it sent be back ofcourse, when i joined the new planet my ships are either missing lots of blocks, or i dont have any ship and i just fall and die

**Comment by BatFC** [comment] 2016-07-09 11:53
There are two types of beaver bugs I know so far:
First is related to boardingramp, blocks that connected to boardingramp sign usually disappears on server transfer along with the sign, one time the whole row that the boardingramp sign was on dissapeared and the rest of my ship was mashed together. little_liggo can provide some more details on the last bug if necessary.
Second is all signs, iron bars and droppers disappear upon server transfer.

**Comment by Millibyte1** [comment] 2016-07-09 23:10
Closing as duplicate of #1077

**Closed as completed by Millibyte1** 2016-07-09 23:10 UTC
