### ISSUE TITLE
Planters Not Working

### ISSUE THREAD

**Issue by PatchyFox** [StarQuestMinecraft/StarQuestPublic#600] opened 2015-07-15 03:18 UTC
Hi there,

I'm sure you're aware of the issue already, but just in case nobody's reported it formally... I have the cert for planterdrill (twice, in fact) and can use Machina Drills just fine. Unfortunately though, when I tried to set up a planter, I received an "insufficient permissions" error. 

I'd love to be able to start farming soon - any idea when this will be fixed?

Thanks, 
-PatchworkFox

**Comment by awangatboo** [comment] 2015-07-15 12:57
This is a duplicate of #561.  Please close this ticket and follow what the issue is on Ticket #561.

**Closed as completed** 2015-07-15 23:00 UTC
