### ISSUE TITLE
Killing people multiple times in gamma kicks and kills you.

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#682] opened 2015-08-18 00:56 UTC
Not so much of a bug, but, when I was pirating in gamma, I attacked this one person, whom I killed, and whom had a cryopod on his ship. He then repeatedly respawned, trying to come after me. Each iteration he tried this, and each iteration, I killed him. However, the server kicked me for kill abuse (2.0 feature I assume) and the combat logging plugin killed me. I logged back in dead.

**Comment by awangatboo** [comment] 2015-08-18 11:18
Per talking to management.  This is not a bug but a "feature".  Closing Ticket

**Closed by awangatboo** 2015-08-18 11:18 UTC

**Comment by awangatboo** [comment] 2015-08-18 11:20
From management "You kill someone like more than 7 times you get kicked"
