### ISSUE TITLE
Alpha has PvP Enabled Now?

### ISSUE THREAD

**Issue by flaammeer** [StarQuestMinecraft/StarQuestPublic#553] opened 2015-07-03 07:01 UTC
well i was going to spawn to pick up two friends from spawn when some one attacked me i figured he couldnt attack me so i lost diamond armor and im going to lose power which i need now im 1 more  step closer to losing my fac and i would also like a refund unless somehow my ship is rebuilt and i survive space which im pretty sure i will die 

and i also took some screenshots but i just want the diamond gear back i dont care about the buckets and stuff

**Comment by flaammeer** [comment] 2015-07-03 07:05
i have screenshots also before my death

**Comment by awangatboo** [comment] 2015-07-09 20:54
Dib stated that PVP would be off in Alpha for a while.  From your experience we can tell it is now on.  Anyone can see this by issuing the command /rg info.  This is not a Bug and any refunds should be taken up with Mods.

Please close this ticket

**Closed as completed** 2015-08-08 13:19 UTC
