### ISSUE TITLE
/stats perms are disabled

### ISSUE THREAD

**Issue by AlinaFicalton** [StarQuestMinecraft/StarQuestPublic#603] opened 2015-07-15 11:02 UTC
so i tryed to see the stats of the new ship class i unlocked and one i was intrested in with /stats (shipclass name). when i tryed it it tell me this: "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error" witch is is sence the certs page is telling us to use it.

**Comment by Tonlage** [comment] 2015-07-15 12:36
This is a duplicate of #597.

**Comment by awangatboo** [comment] 2015-07-15 18:39
Seeing that this is a duplicate of #597 please close this Ticket

**Closed as completed** 2015-07-16 02:22 UTC
