### ISSUE TITLE
Beam Transporters!

### ISSUE THREAD

**Issue by SamvWrath** [StarQuestMinecraft/StarQuestPublic#1088] opened 2016-07-07 00:19 UTC
Hey! I love this idea, especially for dense planets but there are 3 bugs I found in the first 4 mins of testing it.

1: It seems to break the top block of your ship directly over the beam transporter. What I mean by this is that the glass that descends or goes up must start above your ship or something. 

2: If you try to beam down on stained glass, itll break right through. The beam probably thinks that the glass is a hangar shield so you'll lose your shield in the process.

3: Sometimes when you beam up, it takes the block directly under the area you beamed up. If you were to beam up starting at a diamond block, you might lose that block!

**Comment by martinjonsson01** [comment] 2016-07-07 12:15
Hey, thanks for reporting these bugs. Helps me out a lot. 

1: I found the problem, and it should be fixed now. 

2: I couldn't reproduce the glass disappearing when beaming down, only when beaming up. And that only occurs when the stained glass is the same color as the stained glass on your beam transporter(see explanation below). I'll see if I can fix that, too.

3: That should only happen if the stained glass you're beaming down on is the same color as the stained glass in your beam transporter. I was aware of this, but it was not the easiest to fix so instead I hoped nobody would notice it. I'll try to get that fixed now, but you should know that you won't lose anything like a diamond block, worst case, you lose a peice of stained glass.

EDIT: 2: I've fixed the problem of stained glass of the same color as the beam transporter disappearing when beaming up from it.

**Comment by martinjonsson01** [comment] 2016-07-10 14:18
These should be fixed now, re-open the issue if they're not.

**Closed as completed by martinjonsson01** 2016-07-10 14:18 UTC
Labels: Priority Med
