### ISSUE TITLE
Tank Armor 3 upgrade broken

### ISSUE THREAD

**Issue by TacoLink** [StarQuestMinecraft/StarQuestPublic#683] opened 2015-08-18 20:43 UTC
Reporting for Will_Hamilton.

Tank armor 3 upgrades are not achievable by infamy, even though they specifically state they *are*. He has the money and the points, however it is not accepted specifically because of the points, even though he has enough of. He had no problem getting the previous 2 upgrades with infamy. The upgrade is noted as being Piracy or Privateering related, not just privateering.

**Comment by awangatboo** [comment] 2015-08-18 22:59
I will check with management but I think tank armor 3 can only be unlocked with reputation.  It is the same way with the ships.

**Comment by Kyle98martin** [comment] 2015-08-21 14:07
The only bug is it saying it is unlockable with infamy. He shouldn't be able to unlock armour 3 with infamy since it's exclusive to the privateering path just like guns 3 is exclusive to the piracy path.

**Comment by awangatboo** [comment] 2015-08-21 21:03
I have confirmed this with SQ management.  Just like Kyle said.  Armor 3 = privateering.  I will ask staff to make sure the text says that.

**Comment by awangatboo** [comment] 2016-04-20 18:55
Closing all bugs in preparation for SQ 4.0.

**Closed by awangatboo** 2016-04-20 18:55 UTC
Labels: Priority low
