### ISSUE TITLE
New Username, Chests Are Private To My Old One

### ISSUE THREAD

**Issue by Cariadd** [StarQuestMinecraft/StarQuestPublic#1033] opened 2016-06-12 11:38 UTC
My old user is Cariadd, my new user is Treesus_The_Tree. One of my freighters cannot be reclaimed as i have private signs there and 2 of my chests have private signs to my old user.

**Comment by gregolegomonkey** [comment] 2016-06-20 20:47
This is not a bug, and you are responsible for any issues that arise as a result of changing your username.  This is stated in the server rules, and your issue will likely not be fixed by staff.

**Comment by GingerWalnut** [comment] 2016-07-09 18:51
^ and this might be fixed at the next restart.

**Closed as completed by GingerWalnut** 2016-07-09 18:51 UTC
