### ISSUE TITLE
Player entity dissappearing when unpiloting ship

### ISSUE THREAD

**Issue by gregolegomonkey** [StarQuestMinecraft/StarQuestPublic#621] opened 2015-07-21 00:39 UTC
Player entity dissapeared after the player unpiloted the ship.  The player was visible prior to unpiloting.  The player was DangerP7 piloting ship of class Fighter, this happened near the TB slipgate in TA.  The two of us were the only ones present.

**Comment by awangatboo** [comment] 2015-07-21 01:10
This happens everywhere.

**Comment by icekoob** [comment] 2015-07-21 18:23
This is because of 1.8

**Comment by awangatboo** [comment] 2015-08-09 01:56
I just realized this is a duplicate of #259.  Closing this bug.  #259 states it is unfixable but my guess is that at some point it might be fixed but it will take a new spigot version before we get there.

**Closed as completed by awangatboo** 2015-08-09 01:56 UTC
Labels: Duplicate
