### ISSUE TITLE
Ship Pilots Invisible

### ISSUE THREAD

**Issue by ConnorXConnor** [StarQuestMinecraft/StarQuestPublic#476] opened 2015-05-31 23:58 UTC
It seems that some people are seeing people currently flying ships as invisible. I noticed a player that it was happening to. Then I asked everyone if they've had similar issues and several confirmed it. Probably could be a very damaging bug.
-EnderTizzy

**Comment by Dibujaron** [comment] 2015-06-01 16:08
That's been a problem for awhile. It's a spigot bug and there's not a lot we can do about it unfortunately.

**Comment by Siigillum** [comment] 2015-06-01 17:13
Quick relog is the temporary fix for this. Till ship moves again...

**Comment by GroxTerror** [comment] 2015-06-05 05:06
It affects everything around the ship as well, including you, if you aren't even piloting it. Kyra got a taste of this the other night while trying to smash me against a wall with a gunship.

**Comment by awangatboo** [comment] 2015-09-02 15:59
Duplicate of #259

**Closed as completed by awangatboo** 2015-09-02 15:59 UTC
