### ISSUE TITLE
Cant server jump

### ISSUE THREAD

**Issue by samshamrock12** [StarQuestMinecraft/StarQuestPublic#1181] opened 2016-08-06 21:01 UTC
So everytime i try entering a planet or anything other than the spawn ship it will say preparing to server jump like normal, but then it just wont sever jump.I've sat there for a good ten minutes and try'd relogging.I've tried asking moderators or admins but everytime theres either none on or they're not answering me.

**Comment by Millibyte1** [comment] 2016-08-07 02:41
Closed as duplicate of #1170

**Comment by Millibyte1** [comment] 2016-08-07 04:13
You said other people were able to server jump, were these people in the same system as you?

**Comment by Millibyte1** [comment] 2016-08-09 18:59
This issue should be resolved

**Closed as completed by Millibyte1** 2016-08-09 18:59 UTC
