### ISSUE TITLE
Welcome the new Trinity beavers devs!

### ISSUE THREAD

**Issue by Consue** [StarQuestMinecraft/StarQuestPublic#647] opened 2015-08-02 21:38 UTC
so I was traveling and out of no where part of my ship hits the unloaded chunk zone and a beaver eats that part of my ship, then the ship gets its senses back and stops the auto pilot realizing that part of the ship is in the un loaded zone but its too late and the chunk loaded up empty
this happened in beta

**Comment by awangatboo** [comment] 2015-08-03 12:54
Please give data and time to make it where the logs can be looked at to see what the issue is.

**Comment by awangatboo** [comment] 2015-08-05 19:41
I have had this issue as well but without details as to when it happened (date / time) I am not sure it will help find the issue.

**Comment by awangatboo** [comment] 2015-08-27 02:28
Closing this issue as there is not enough info to reproduce

**Closed as completed by awangatboo** 2015-08-27 02:28 UTC
