### ISSUE TITLE
Stuck In Samp Air Because Of Weird Glitch

### ISSUE THREAD

**Issue by rocky0121** [StarQuestMinecraft/StarQuestPublic#818] opened 2016-02-09 06:59 UTC
I was flying from trinitos beta north station, to samp. when i entered the atmosphere of samp, i  couldnt repilot because there were too little wool blocks. During  the flight to samp, no attacks from either other pirates or skywatch was made. Plz halp.

**Comment by awangatboo** [comment] 2016-02-10 16:21
This is the normal ship bug that can happen.  I think the issue is that sometimes when you start a ship up it does not detect all the blocks.  Then you fly without seeing that part of your ship is missing and then your fly into a planet and you can not re-pilot because your ship is gone.  Ask a Mod in-game to reload your ship.  This is definitely a bug.

**Comment by awangatboo** [comment] 2016-04-20 18:33
Closing all bugs in preparation for SQ 4.0.

**Closed as completed by awangatboo** 2016-04-20 18:33 UTC
Labels: Priority Med
