### ISSUE TITLE
Died while using a hangglider to get off a mountain to fight off skywatch which shouldn't have been summoned on me in the first place

### ISSUE THREAD

**Issue by FlyingTaurus523** [StarQuestMinecraft/StarQuestPublic#781] opened 2015-12-15 23:13 UTC
on eratoss I was attacking someone I wasn't wanted or privateer they both were wanted. One of them combat tagged me and I didn't hurt them and skywatch got summoned on me, so I hangglided off the mountain to fight skywatch and I died to fall damage. Could this please be fixed and I get a refund?

**Comment by awangatboo** [comment] 2015-12-15 23:57
Did you have thorns on your armor?  If so that would explain it.

**Comment by awangatboo** [comment] 2015-12-16 00:58
Nick you will need to make the call as to the handglyder issue.

**Comment by Tank0696** [comment] 2015-12-16 03:02
Glitch? or just you trying to get your gear back because your Buthert

**Comment by Siigillum** [comment] 2015-12-16 12:47
If they shoot you while gliding the glider drops/breaks.

Also you should have privateer contract so you could attack them and not get skywatched. And if you did nto have priv contract thorns could have enabled the skywatch.

**Comment by Siigillum** [comment] 2015-12-16 12:47
They = players or mobs. Damage is suppsoed to break a glider mid air.

**Comment by awangatboo** [comment] 2015-12-16 14:31
Sigg answered the question about the glider breaking and seeing that you said in game that you did have thorns on this is not a bug / glytch.

**Comment by Siigillum** [comment] 2015-12-16 15:07
Summing up. Not the best glider pilot around :p

**Comment by FlyingTaurus523** [comment] 2015-12-16 22:27
I wasn't shot, it was a very smooth hangglide to the bottom of a sloped mountain so even if I did get shot in midair I shouldn't have died from fall damage and I wasn't shot in midair. basically when I just hit the ground from hanggliding it just instakilled I didn't see any skywatch, and I understand how skywatch was triggered cause I did have thorns.

**Comment by Nickmiste** [comment] 2015-12-19 01:18
Did your hang glider break in midair, or did you glide to the ground but still take fall damage?

**Comment by FlyingTaurus523** [comment] 2015-12-19 14:44
no, it didn't break in midair, I glided all the way to the ground and just died.

**Comment by Siigillum** [comment] 2015-12-19 15:52
He was gliding saing: yes yes nice yes. Then: SPLAT! NOPE!

**Comment by awangatboo** [comment] 2016-04-20 18:44
Closing all bugs in preparation for SQ 4.0.

**Closed as completed by awangatboo** 2016-04-20 18:44 UTC
Labels: Priority low
